### PR TITLE
feat: ACNA-2783 - front-end hot reload

### PR DESCRIPTION
**Pull request by shazron**
This enables front-end hot reload.
This PR incorporates changes from original PR #14 (which has been closed)

## How Has This Been Tested?

- local link of the plugin
- debug in VS Code of an AB project after running `aio app dev init`
  1. choose the "Debug" tab in the sidebar
  2. choose the "App Builder: debug full stack" configuration in the Debug dropdown menu
  3. select the green "Play" button
  4. wait for the Chrome browser (required) to launch
  5. edit any Javascript or HTML in the web-src folder
  6. observe the changes reflected in the browser
- unit tests are expected to fail since we haven't completed unit tests yet

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by MichaelGoberling — APPROVED** [review]

**Review by moritzraho — APPROVED** [review]

**Comment by purplecabbage** [comment]
When I run app dev with this, I am forced to choose whether to overwrite, or merge vscode config.
This opens a new window every time ... it should only open a window if --open is true

**Comment by purplecabbage** [comment]
The additions of aio-logger mean that where we used to output

```
server running on port : 9080
629 static asset(s) changed
✨ Built 3 bundles in 1964ms!
```

we now output 

```
2024-04-25T00:58:07.400Z [@adobe/aio-cli-plugin-app-dev:bundle-serve] info: server running on port : 9080
⠴ 2024-04-25T00:58:09.506Z [@adobe/aio-cli-plugin-app-dev:bundle-serve] info: 629 static asset(s) changed
2024-04-25T00:58:09.507Z [@adobe/aio-cli-plugin-app-dev:bundle-serve] info: ✨ Built 3 bundles in 1964ms!
```

This seems to me like a step in the wrong direction.

**Comment by purplecabbage** [comment]
> When I run app dev with this, I am forced to choose whether to overwrite, or merge vscode config. This opens a new window every time ... it should only open a window if --open is true

new chrome window is only when run from vscode-ui, it is the debugWithChrome action so it is probably fine

**Comment by shazron** [comment]
> This seems to me like a step in the wrong direction.

It's just a simple change to the provider. I thought for debugging it's better to know timestamps of when things happen.

**Comment by shazron** [comment]
> new chrome window is only when run from vscode-ui, it is the debugWithChrome action so it is probably fine

so your comment is resolved?

**Comment by shazron** [comment]
added https://github.com/adobe/aio-cli-plugin-app-dev/pull/15/commits/15a873c3fdc719b6efd56df1a4e7b8007f92c4d5 to remove the `aio app dev init` call at the start of the `dev` command

**Comment by shazron** [comment]
removed `aio app dev init` command - existing users can read an upgrade doc https://github.com/adobe/aio-cli-plugin-app-dev/pull/15/commits/5022877ce10156812ae394f0d88255c2a0cc4c22

**Comment by shazron** [comment]
Closed PR #14 in favor of this one.

**Pull request merged**
